#! /bin/bash

function print_usage()
{
cat <<EOF
Usage: preview [options] [FILE]

'preview' allows you to quickly preview a file from its source, for example markdown files.
It uses the 'entr' command to monitor the source file and automatically update the preview.

'preview' uses a makefile to execute the commands required to build, view, and refresh the preview.
If a makefile is found in the current directory, it will be used, otherwise a default makefile is used.
If you choose to use your own makefile, you must define the following targets

build - This target should build the output file to be viewed from your source. By default 'preview' uses pandoc to generate an html
        file from markdown source. This target will be ran each time the source file is updated (saved).

view  - This target should open the output file in a viewing program. By default 'preview' uses vimb to open the html
        file that was generated with the build target.

refresh - This target should refresh the viewer. By default 'preview' uses the socket communication feature of vimb to send refresh commands.

These targets are optional.

outfile - This target should print the name of the output file (the file that will be viewed with the viewer).
          By default, 'preview' generates the output filename by replacing all slashes (/) and periods (.) with underscores (_),
          then appendeng a ".html" extension and prepends the name of the temp directory (see below)

These variables will be passed into the makefile by 'preview', and can be used in your targets.

INFILE  - the name of the source file to be previewed.
OUTFILE - the name of the generated file that will be viewed by the viewer
TMPDIR  - the name of a temperary directory that has been created by 'preview'. If you want the output files to be generated in a temp
          directory, you should prepend the output filename with this directory.

Dependencies:
  Required:
    - docopts : command line parser for shell scripts

  Optional:
    - pandoc : used by preview's default makefile to build html from markdown
    - vimb : used by preview's default makefile to view html
    - socat : used by preview's default makefile to refresh preview

You can run:
  > preview -p
to see the makefile that is used by 'preview' by default.

Options:
      -p --print-makefile  Show makefile and exit.
      -f --makefile FILE Use FILE instead of default makefile.


EOF
}

# the getopt command is external to the shell. essentially what it
# does is parse the command line parameters and rearrange them so
# that all of the options are given before any of the arguments, and
# adds a '--' between the options and arguments. 
# then you can setup a while loop to process options easily and terminate
# it when you run into the '--'

# both long and short options can be given
# short options are passed to -o
# long  options are passed to -l
# a colon (:) after an option means it has a required argument
# two colons (::) after an option means it has a optional argument


NEW_COMMAND_LINE=$(getopt -o hpf: -l print_makefile,help,makefile: -n preview -- "$@")   # this creates a rearranged version of the command line
if [ $? != 0 ] ; then echo "getopt returned an error, Terminating..." >&2 ; exit 1 ; fi
eval set -- "$NEW_COMMAND_LINE"                                                                          # this sets up positional parameters to the new command line


# now we can just manually loop through the positional parameters
print_makefile=0
makefile=""
while true ; do
  case "$1" in
    -h|--help)
        print_usage
        exit;
        ;;
    -p|--print_makefile)
        print_makefile=1
        shift 1
        ;;
    -f|--makefile)
        makefile=$2
        shift 2
        ;;
    --) shift ; break ;;
     *) echo "Unreconized option got through: '$1'" ; exit 1 ;;
  esac
done

# arguments start at $1...

ifile=${1}
shift

if [ ! $ifile ]; then
  if which Xdialog 2>&1 > /dev/null
  then
    ifile=$(Xdialog --no-buttons -fselect '' 0 0 2>&1)
  #elif which dialog 2>&1 > /dev/null
  #then
    #ifile=$(dialog --fselect '' 0 0)
  else
    read -p "What file would you like to preview?" ifile
  fi
fi

tmpdir=$(mktemp -d)

# try to find a makefile
wd=$(dirname $ifile) # directory that the source file is in
ext=${ifile##*.}     # extension of the source file

if [ ! -e "$makefile" ]
then
  # look for a Makefile with the same extension as the input file
  # in the same directory as the input file
  makefile="$wd/Makefile.$ext"
fi

if [ ! -e "$makefile" ]
then
  # look for a Makefile with the same extension as the input file
  # in the .preview directory
  makefile="~/.preview/Makefile.$ext"
fi

if [ ! -e "$makefile" ]
then
  # look for a Makefile
  # in the same directory as the input file
  makefile="$wd/Makefile"
fi

if [ ! -e "$makefile" ]
then
  # look for a Makefile in the directory we where called from
  makefile="~/.preview/Makefile"
fi

if [ ! -e $makefile ] 
then
# create a makefile
makefile=${tmpdir}/Makefile
cat >$makefile << 'EOF'
outfile:
	@echo $(TMPDIR)/$$( echo $(INFILE)  | sed 's|/|_|g' | sed 's|\.|_|g').html

build:
	@pandoc -f markdown -t html -o $(OUTFILE) $(INFILE)

view:
	@vimb -s -d file://$(OUTFILE) 1>$(TMPDIR)/_socket 2>/dev/null

refresh:
	@echo ':o file://$(OUTFILE)<CR>' | socat - UNIX-CONNECT:`tail -n 1 $(TMPDIR)/_socket`
EOF
fi

if [ $print_makefile -eq 1 ]
then
  cat $makefile
  exit
fi

ifile=$(readlink -f $ifile)
make="make -f $makefile INFILE=${ifile} TMPDIR=${tmpdir}"


if $make outfile > /dev/null 2>&1
then
  ofile=$($make outfile)
else
  ofile=${tmpdir}/$( echo ${ifile}  | sed 's|/|_|g' | sed 's|\.|_|g').htmlxx
fi
make="$make OUTFILE=${ofile}"





$make build > /dev/null
$make view &
viewPID=$!
sleep 0.1

ls $ifile | entr sh -c "$make build && $make refresh" &
entrPID=$!

wait $viewPID
kill $entrPID
