#! /bin/bash

eval "$(docopts -h - : "$@" <<EOF
Usage: preview [options] <file>

      -p --print-makefile  Show makefile and exit.

EOF
)"

ifile=${file[0]}
shift

tmpdir=$(mktemp -d)
ifile=$(readlink -f $ifile)
ofile=${ifile//\//_}
ofile=${ofile//./_}
ofile=${tmpdir}/${ofile}.html

makefile="Makefile"
if [ ! -e $makefile ] 
then
makefile=${tmpdir}/Makefile
cat >$makefile << 'EOF'
INFILE=test.md
OUTFILE=$(PWD)/test.md.html

build:
	pandoc -f markdown -t html -o $(OUTFILE) $(INFILE)

view:
	vimb -s -d file://$(OUTFILE) 1>_socket 2>/dev/null

refresh:
	echo ':o file://$(OUTFILE)<CR>' | socat - UNIX-CONNECT:`tail -n 1 _socket`
EOF
fi

if $print_makefile
then
  cat $makefile
  exit
fi




make="make -f $makefile INFILE=${ifile} OUTFILE=${ofile}"


$make build
$make view &
viewPID=$!
sleep 0.1

ls $ifile | entr sh -c "$make build && $make refresh" &
entrPID=$!

echo $viewPID
echo $entrPID

wait $viewPID
kill $entrPID
